### ISSUE TITLE
Great work!  REQUEST - addition, of shmsink and rtmpsink for external connection for playout

### ISSUE THREAD

**Issue by TVforME** [dorftv/dove#15]
Hello @hatsch and team,
Great work!!  

I too been looking at brave and voctomix as inspiration.  I'm was also developing  AV mixer for my repeater projects and come across this repo..   

I'd like to help however, I'm refactoring your code base over from Python to GO to add a some features and other things and leverage of GO's coroutines and parallelism. GO makes the transitioning both the volume and alpha easy without the need for glib and gst-controller. 

Could was add shmsink and rtmpsink as outputs to allow for streaming to external programs to connect with dove's output?

I'd suggest an event loop to monitor for bus error on element rtmp2sink to signal a network issue and wait x seconds before attempting a reconnect. I've done so using go however, opted to use a timed net connection to the rtmp port on the remote server every 10 seconds for a response before beginning to build the RTMP pipeline from scratch.  Using pad probes and ghost pads become problematic, so I opted to just set the pipeline to NULL and rebuild a fresh pipeline once the remote server was back online.  

Go to see interpipe in the mix also maybe an idea to check if the hardware has GPU support and adjust elements to use nvdecode/encode over software and nvcompositor etc?  Assuming NVIDIA hardware is available with correct drivers and nv Gstreamer plugins are on the machine.

I don't understand why interpipe is yet to be put in mainstream Gstreamer?  Maybe 1.36?

**Comment by hatsch** [comment]
Hello @TVforME,
thanks for your comment! This project started as a python project because we initially tried to update/enhance BRAVE which was not working as hoped. So we rebuilt from scratch.
I guess there are better suited languages these days ( Go, but probably with even better gstreamer support RUST), but ressources on our side are scarce. I am even behind updating docs to ease collaboration with others.
there is also the dove-frontend project where work on the frontend is happening. this could be a collaboration starting point, as the frontend doesn't care about the language the backend is written, as long as the API is the same.

adding additionally sinks should be rather trivial. it's enough to add it to /api/outputs/newsink.py and pipeline/outputs/newsink.py and DOVE should pick it up. Only for adding it on startup via config.toml there is an additional step in element_factory.py. plan is to detect that automatically too. 

as for additional sinks there is another task open. choosing the encoder and respective options.
if you look in develop branch, i started work on adding x264 options and h264 profile. also audio codec needs to be set somehow ( eg we will need mp2 audio in srt for TV broadcasting) 

i'm not quite sure how to handle this best.

answers might be a little bit delayed at the moment as it is holliday season right now.

**Comment by hatsch** [comment]
as you can see in this commit ( https://github.com/dorftv/dove/commit/4b397fe7bdfef6985ac5a885ffdb2532a9092ac8 ) i recently added basic rtmpsink.
closing this issue now. please open new issues for single feature requests as needed to make it easier to follow.

**Comment by TVforME** [comment]
Hi @hatsch ,

Thank you for your effort in adding RTMP.  I'll look at adding RTMP restart on network error to restart the pipeline when the end point drops out.  The rtmp2sink is my choice over the early rtmpsink. In addition,  how did you install wpe on machine? gstreamer1.0-wpe is not available as a package?
